---
title: "Join the lab"
---

# Prospective PhD Students

My students enroll in the [PhD program in Environmental Science and Policy](https://abess.miami.edu/academics/ph.d.-program/index.html), jointly administered by the [Abess Center](https://abess.miami.edu/) and the [Department of Environmental Science and Policy](https://environmental-science-policy.earth.miami.edu/index.html) at the University of Miami. Students will also be part of the [Earth System Science](https://idsc.miami.edu/research/earth-systems/) initiative at the Institute for Data Science and Computing.

Note that students don't join the lab to work on specific projects. You will have the opportunity to develop your own research projects, so long as they align with [our three pillars](about.qmd#our-three-pillars). Additionally, my PhD students are required to enroll in the PhD Econometrics sequence at the Department of Economics to gain proficiency in causal inference techniques, as well as my [Intro to Environmental Data Science](https://jcvdav.github.io/EVR_628/) class. Students may also opt to gain these skills via independent study or to substitute them for other quantitative skills (e.g. machine learning). All students are expected to be/become proficient in at least one scripting language (R / Python), as well as version control via git and GitHub.

## PhD Positions for Fall '26

I am hoping to recruit up to two **fully funded** PhD students to start in Fall 2026. [Prospective students should contact me^[email: jc_villasenor@miami.edu] well in advance of the application deadline.]{.underline} Please include your CV and a 1-pager (max) description of your past experience in academic research, your research interests, and your motivations for pursuing a PhD.

# Undergraduate students

Undergraduate students interested in joining my lab may do so via [MSC 411 / 412](https://undergraduate.earth.miami.edu/academics/independent-research/index.html). Please contact me to inquire about potential opportunities. You should be comfortable working independently in R. A great resource to get you started is the [R for Data Science](https://r4ds.hadley.nz/) book, as well as my [course materials](https://jcvdav.github.io/EVR_628/).

# MS Students

I don't actively recruit students to enroll in our Master of Sciences program unless you are bringing in your own funding. I am happy to work with you in securing your own funding.
