---
title: "Outputs"
title-block-banner: img/JCV_313.jpg
---

::: panel-tabset
## Peer-reviewed publications

<!-- Use Vancouver citation style -->

### 2026
- **Villaseñor-Derbez JC**, Fernández R, Fulton S, Hernández-Velasco A, Hernández T, Woodson CB, Cárdenas JC, DeLeo GA, Torre J, Micheli F. Digital technologies and the study of adaptation in small-scale fisheries. _Ocean & Coastal Management_. 2026 Apr 1;275:108071. doi: [doi.org/10.1016/j.ocecoaman.2025.108071](https://doi.org/10.1016/j.ocecoaman.2025.108071)

### 2025

- **Villaseñor-Derbez JC**, Lynham J, Garibay-Toussaint I, Narchi NE, O’Connor R, Olguín-Jacobson C, DeLeo GA, Torre J, Arafeh-Dalmau N, Fulton S, Woodson CB. Climate-resilient fisheries are more resilient in general. _npj Ocean Sustainability_. 2025 Nov 11;4(1):56. doi: [doi.org/10.1038/s44183-025-00154-1](https://doi.org/10.1038/s44183-025-00154-1)
- Arafeh-Dalmau N, **Villaseñor-Derbez JC**, Schoeman DS, Mora-Soto A, Bell TW, Butler CL, et al. Global floating kelp forests have limited protection despite intensifying marine heatwave threats. _Nature Communications_. 2025;16: 3173. doi: [doi.org/10.1038/s41467-025-58054-4](https://doi.org/10.1038/s41467-025-58054-4)
- Englander G, Zhang J, **Villaseñor-Derbez JC**, Jiang Q, Hu M, Deschenes O, et al. Input subsidies and the depletion of natural capital: Chinese distant water fishing. _J Environ Econ Manage_. 2025;130: 103127. doi:[10.1016/j.jeem.2025.103127](https://doi.org/10.1016/j.jeem.2025.103127)

### 2024

- Lynham J, **Villaseñor-Derbez JC**. Evidence of spillover benefits from large-scale marine protected areas to purse seine fisheries. _Science_. 2024;386: 1276–1281. doi:[10.1126/science.adn1146](https://doi.org/10.1126/science.adn1146)
- Kumagai JA, Goodman MC, **Villaseñor-Derbez JC**, Schoeman DS, Cavanuagh KC, Bell TW, et al. Marine protected areas that preserve trophic cascades promote resilience of kelp forests to marine heatwaves. _Glob Chang Biol_. 2024;30: e17620. doi:[10.1111/gcb.17620](https://doi.org/10.1111/gcb.17620)
- **Villaseñor-Derbez JC**, Arafeh-Dalmau N, Micheli F. Past and future impacts of marine heatwaves on small-scale fisheries in Baja California, Mexico. _Commun Earth Environ_. 2024;5: 623. doi:[10.1038/s43247-024-01696-x](https://doi.org/10.1038/s43247-024-01696-x)
- **Villasenor-Derbez JC**, Costello C, Plantinga AJ. A market for 30x30 in the ocean. _Science_. 2024;384: 1177–1179. doi:[10.1126/science.adl4019](https://doi.org/10.1126/science.adl4019)

### 2023

- Arafeh-Dalmau N, Munguia-Vega A, Micheli F, Vilalta-Navas A, **Villaseñor-Derbez JC**, Précoma-de la Mora M, et al. Integrating climate adaptation and transboundary management: Guidelines for designing climate-smart marine protected areas. _One Earth_. 2023;6: 1523–1541. doi:[10.1016/j.oneear.2023.10.002](https://doi.org/10.1016/j.oneear.2023.10.002)
- **Villaseñor-Derbez JC**, Fulton S, Hernández-Velasco A, Amador-Castro IG. Biomass accrual benefits of community-based marine protected areas outweigh their operational costs. _Front Mar Sci_. 2023;10: 1180920. doi:[10.3389/fmars.2023.1180920](https://doi.org/10.3389/fmars.2023.1180920)
- Pearson HC, Savoca MS, Costa DP, Lomas MW, Molina R, Pershing AJ, et al. Whales in the carbon cycle: can recovery remove carbon dioxide? _Trends Ecol Evol_. 2023;38: 238–249. doi:[10.1016/j.tree.2022.10.012](https://doi.org/10.1016/j.tree.2022.10.012)

### 2022

- Wilson MW, Lawson JM, Rivera-Hechem MI, **Villaseñor-Derbez JC**, Gaines SD. Evaluating conditions for moored fish aggregating device fisheries development in the Caribbean and Bermuda. _Front Mar Sci_. 2022;9: 827068. doi:[10.3389/fmars.2022.827068](https://doi.org/10.3389/fmars.2022.827068)
- **Villaseñor-Derbez JC**, Amador-Castro IG, Hernández-Velasco A, Torre J, Fulton S. Two decades of community-based marine conservation provide the foundations for future action. _Front Mar Sci_. 2022;9: 893104. doi:[10.3389/fmars.2022.893104](https://doi.org/10.3389/fmars.2022.893104)
- Wintergalen EW, Oyanedel R, **Villaseñor-Derbez JC**, Fulton S, Molina R. Opportunities and challenges for livelihood resilience in urban and rural Mexican small-scale fisheries. _Ecol Soc_. 2022;27. doi:[10.5751/es-13471-270346](https://doi.org/10.5751/es-13471-270346)

### 2021

- Ramírez-Valdez A, Rowell TJ, Dale KE, Craig MT, Allen LG, **Villaseñor-Derbez JC**, et al. Asymmetry across international borders: Research, fishery and management trends and economic value of the giant sea bass (Stereolepis gigas). _Fish and Fisheries_. 2021;22: 1392–1411.
- Tuholske C, Halpern BS, Blasco G, Villasenor JC, Frazier M, Caylor K. Mapping global inputs and impacts from of human sewage in coastal ecosystems. _PLoS One_. 2021;16: e0258898. doi:[10.1371/journal.pone.0258898](https://doi.org/10.1371/journal.pone.0258898)
- Millage KD, **Villaseñor-Derbez JC**, Bradley D, Burgess MG, Lenihan HS, Costello C. Self-financed marine protected areas. _Environ Res Lett_. 2021;16: 125001. doi:[10.1088/1748-9326/ac3439](https://doi.org/10.1088/1748-9326/ac3439)

### 2020

- Wilson MW, Lawson JM, Rivera-Hechem MI, **Villaseñor-Derbez JC**, Gaines SD. Status and trends of moored fish aggregating device (MFAD) fisheries in the Caribbean and Bermuda. _Mar Policy_. 2020;121: 104148. Available: https://www.sciencedirect.com/science/article/pii/S0308597X20304796
- Lynham J, Nikolaev A, Raynor J, Vilela T, **Villaseñor-Derbez JC**. Impact of two of the world's largest protected areas on longline fishery catch rates. _Nat Commun_. 2020;11: 979. doi:[10.1038/s41467-020-14588-3](https://doi.org/10.1038/s41467-020-14588-3)
- **Villaseñor-Derbez JC**, Lynham J, Costello C. Environmental market design for large-scale marine conservation. _Nature Sustainability_. 2020;3: 234–240.

### 2019

- **Villaseñor-Derbez JC**, Aceves-Bueno E, Fulton S, Suarez A, Hernández-Velasco A, Torre J, et al. An interdisciplinary evaluation of community-based TURF-reserves. _PLoS One_. 2019;14: e0221660. doi:[10.1371/journal.pone.0221660](https://doi.org/10.1371/journal.pone.0221660)
- **Villaseñor-Derbez JC**, Fitzgerald S. Spatial variation in allometric growth of invasive lionfish has management implications. _PeerJ_. 2019;7: e6667. doi:[10.7717/peerj.6667](https://doi.org/10.7717/peerj.6667)
- O'Hara CC, **Villaseñor-Derbez JC**, Ralph GM, Halpern BS. Mapping status and conservation of global at-risk marine biodiversity. _Conservation Letters_. 2019;12: e12651.

### 2018

- **Villaseñor-Derbez JC**, Faro C, Wright M, Martínez J, Fitzgerald S, Fulton S, et al. A user-friendly tool to evaluate the effectiveness of no-take marine reserves. _PLoS One_. 2018;13: e0191821. doi:[10.1371/journal.pone.0191821](https://doi.org/10.1371/journal.pone.0191821)
- Peake J, Bogdanoff AK, Layman CA, Castillo B, Reale-Munroe K, Chapman J, et al. Feeding ecology of invasive lionfish (Pterois volitans and Pterois miles) in the temperate and tropical western Atlantic. _Biological Invasions_. 2018;20: 2567–2597. Available: https://link.springer.com/article/10.1007/s10530-018-1720-5

### 2016

- Hernández-Velasco A, Fernández-Rivera-Melo FJ, Melo‐Merino SM, **Villaseñor‐Derbez JC**. Occurrence of Holacanthus clarionensis (Pomacanthidae), Stegastes leucorus, and Stegastes acapulcoensis (Pomacentridae) at Magdalena Bay, B.C.S., Mexico. _Mar Biodivers Rec_. 2016;9: 1–7. doi:[10.1186/s41200-016-0062-1](https://doi.org/10.1186/s41200-016-0062-1)

### 2015

- Dreyfus-León MJ, Mejía-Trejo A, **Villaseñor-Derbez JC**. Analysis of null sets (zero catch) made by the Mexican tuna purse seine fleet (2000--2013). _Ciencias Marinas_. 2015;41: 85–92.
- **Villaseñor-Derbez JC**, Hernández-Velasco A, Erauskin M, Fulton S, Cota-Nieto JJ, Torre J, et al. Effects of short-term marine reserves on grouper and bass populations. DataMares InteractiveResource http://dx doi org/1013022/M33K52. 2015.

### 2014

- **Villaseñor-Derbez JC**, Herrera-Pérez R. Brief description of prey selectivity and ontogenetic changes in the diet of the invasive lionfish Pterois volitans (Actinopterygii, Scorpaenidae) in the Mexican Caribbean. _Panam J Aquat Sci_. 2014;9: 131–135.

## Working papers

### In review

- Molina R., **Villaseñor-Derbez J.C.**, McDonald G., and McDermott. The Economic and Environmental Cost of Pirate Avoidance. Revise and resubmit at _Nature Communications_ (February 2, 2026: NCOMMS-25-93345) | [working paper](https://doi.org/10.1038/s44183-025-00154-1)
- Schiller L.L., **Villaseñor-Derbez J.C.**, Lynham J., and Worm B. Global impacts of drifting fish aggregating devices on marine protected areas. Revise and resubmit at _Science Advances_ (March 9, 2026: aee6998).
- **Villaseñor-Derbez JC**, Willet Burfoot A, and Molina R. Competitiveness in American Seafood Requires Promoting Fisheries to be Resilient. Fish and Fisheries (March 30, 2026: 1931232). | [working paper](documents/working_papers/resilient_gulf.pdf)

### In prep

- **Villaseñor-Derbez J.C.**, Costello C., and Deschênes O. Natural Experiments Show Fuel Subsidies Amplify Fishing Pressure in Industrial Fisheries. | [working paper](documents/working_papers/subsidies2_0.pdf)
- **Villaseñor-Derbez J.C.** et al., Towards the Study the Generalizability of Adaptive Responses in Small-Scale Fisheries | [working paper](documents/working_papers/generalizable_adaptation.pdf)

## Datasets and Software

### Data Explorers

-[Mex VMS explorer](https://mex-fisheries.github.io/mex_vms_explorer/)

### Datasets

- [MEX-fisheries](https://mex-fisheries.github.io/mex-fisheries/)
- [RFMO Tuna](https://doi.org/10.5281/zenodo.14207429)

### Software

- [`EventHorizon`](https://github.com/jcvdav/EventHorizon): An R Package to build panels for event-study models based on a user-specified time horizon for repeated interventions
- [`EVR628tools`](https://github.com/jcvdav/EVR628tools): An R Package with datasets, palettes, and functions to help in the instruction of [EVR 528 / 628](https://jcvdav.github.io/EVR_628/) Introduction to Data Management and Visualization for Environmental Scientists.

<!-- ## Presentations -->

<!-- ### 2025 -->

<!-- - Rhodes A. An Impromptu Fuel Subsidy Reform Decreases Effort by Tuna Longliners in the Gulf Of Mexico. [GCFI78](https://www.gcfi.org/gcfi78/) -->
<!-- - Villaseñor-Derbez J.C. Subsidizing the tragedy of the commons: Evidence from fuel subsidies in Mexican industrial fisheries. [Workshop on Energy and Environmental Research](https://uhero.hawaii.edu/workshop-on-energy-and-environmental-research/). University of Hawaii. -->
<!-- - Villaseñor-Derbez J.C. Evidence of Spillover Benefits from Large-scale Marine Protected Areas to Purse Seine Fisheries. [2025 Measuring Development Conference](https://cega.berkeley.edu/event/measuredev-biodiversity/). The World Bank. -->


:::
